/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thethongminh.user;

import thethongminh.model.Constants;
import java.nio.ByteBuffer;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.smartcardio.*;
import javax.swing.JOptionPane;
import thethongminh.utils.CardManager;
import thethongminh.utils.CardUtils;
import thethongminh.database.DataConnection;
/**
 *
 * @author ACER
 */
public class Connect extends javax.swing.JFrame {

    CardManager cardManager;
    private static ResponseAPDU response;

    /**
     * Creates new form Connect
     */
    public Connect() {
        initComponents();
        setLocationRelativeTo(null);
        cardManager = CardManager.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConnectCard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConnectCard.setBackground(new java.awt.Color(204, 255, 255));
        btnConnectCard.setText("Kết nối");
        btnConnectCard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnConnectCard.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConnectCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectCardActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Vui lòng kết nối thẻ ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnConnectCard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(btnConnectCard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectCardActionPerformed

          
        
        if (!cardManager.getCardChannel()) {
            return;
        }
     

//        byte[] command = CardUtils.createCommand(
//                new byte[]{Constants.CLA},
//                new byte[]{(byte) 0xA4},
//                new byte[]{(byte) 0x04},
//                new byte[]{(byte) 0x00},
//                new byte[]{(byte) 0x07},
//                Constants.AID_APPLET
//        );
        try {
            response = cardManager.sendApduCommand(Constants.CLA, 0xA4, 0x04, Constants.PARAM_DEFAULT, Constants.AID_APPLET);

            int sw = response.getSW();
            
           
            System.out.println("sw connect res: " + CardUtils.convertSWToHex(sw));

            switch (sw) {
                case Constants.SW_SUCCESS:
                    System.out.println("Connect card successfull");
                    this.setVisible(false);
                    new Login().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Kết nối thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case Constants.SW_AID_NOT_FOUND:

                    JOptionPane.showMessageDialog(null,
                            "AID không tồn tại",
                            "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(null,
                            "Lỗi chưa xác định",
                            "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
            }

        } catch (CardException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnConnectCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnectCard;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
